[project]
name = "katakana-cli"
version = "0.1.0"
description = "Someday I'll read it like a pro, but probably not today."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.1.4",
    "rich>=13.9.4",
]
