# Generated by Django 5.1.4 on 2024-12-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WordStat",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=255)),
                ("corpus", models.CharField(max_length=255)),
                ("correct", models.PositiveIntegerField(default=0)),
                ("incorrect", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
